### ISSUE TITLE
battlefieldseries.de RSS Feed fehler

### ISSUE THREAD

**Issue by opt-natter** [TerranUlm/MyBB-Plugin-OPT-Portal#2]
Anscheinend hat battlefieldseries den https zwang abgeschafft und https gleich komplett abgeschaltet. 
Es muss wieder die http url verwendet werden.

**Comment by TerranUlm** [comment]
War auch Zeit, das war eh falsch konfiguriert, so hatte das keinen Sicherheitsgewinn gebracht. Und für News ist sowas auch nicht wirklich nötig.

**Comment by TerranUlm** [comment]
Ist umgesetzt.
